apiVersion: v1 # api 文档版本
kind: Pod
metadata:
  name: nginx-liveness-probe
  labels:
    tpye: app
    test: 1.0.0
  namespace: 'default'
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    startupProbe:
      # httpGet:
      #   path: /index.html
      #   port: 80
      # tcpSocket:
      #   port: 80
      exec:
        command:
        - sh 
        - -c
        - "sleep 3; echo 'aaaa'; echo 'hello' > a.txt"
      initialDelaySeconds: 0
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    livenessProbe:
      httpGet:
        path: /start.html
        port: 80
      # tcpSocket:
      #   port: 80
      initialDelaySeconds: 0
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5

    command:
    - nginx
    - -g
    - 'daemon off;'
    workingDir: /usr/share/nginx/html
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    env:
    - name: JVM_OPTS
      value: '-Xms128m -Xmx128m'
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  restartPolicy: OnFailure