apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-svc
  name: nginx-svc
spec:
  ports:
  - name: http # Service 端口的名称
    port: 80 # Service 自己的端口
    protocol: TCP # UDP TCP SCTP
    targetPort: 80 # 后端应用的端口
  selector:
    app: nginx 
