apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: busybox-1
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 84000
    volumeMounts:
    - mountPath: /tmp/leitong-1
      name: cache-volume 
  - name: busybox-2
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 84000
    volumeMounts:
    - mountPath: /tmp/leitong-2
      name: cache-volume
  volumes: 
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi