apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 84000
    volumeMounts:
    - mountPath: /tmp/leitong  # 挂在到容器的哪个目录
      name: test-volume # 挂在到哪个 volume
  volumes: 
  - name: test-volume
    hostPath: # 加载主机目录到容器中
      path: /tmp/leitongaaa # 节点目录
      type: Directory # 文件夹类型