apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 84000
    volumeMounts:
    - mountPath: /tmp/leitong
      name: test-volume
  volumes: 
  - name: test-volume
    hostPath:
      path: /tmp/leitongaaa
      type: Directory