apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: nginx-svc-external
  name: nginx-svc-external
  namespace: default
subsets:
- addresses:
  - ip: 120.232.145.185
  ports:
  - name: http
    port: 80
    protocol: TCP